### ISSUE TITLE
Enabling OpenGL (on Raspbian) breaks OpenGL ES (in X and console-only apps)

### ISSUE THREAD

**Issue by WayneKeenan** [anholt/mesa#27]
Hi,

Is it expected behaviour that if OpenGL support is enabled then OpenGL ES applications can no longer run ?

There's a bit of a trail starting here: RPi-Distro/raspi-config/#21

Regards
Wayne

**Comment by anholt** [comment]
Applications built against the closed GL stack won't work, because the closed one uses a vendor-specific window system implementation.  That's why EGL is such a disaster of an API.  If you want to build apps supporting multiple window systems (X11 and dispmanx, for example), you'd need https://www.khronos.org/registry/egl/extensions/EXT/EGL_EXT_platform_base.txt.

**Comment by anholt** [comment]
Since Mesa has the extensions for apps to appropriately decide whether they can run on the implementation, I'm closing this as a bug for Mesa.
