### ISSUE TITLE
X: Low performance on LXDE's pcmanfm selection rectangles

### ISSUE THREAD

**Issue by cringeops** [anholt/mesa#47]
I found it out while reading some fancy dmesg logs on my RPi3 with GL driver enabled.
How to reproduce:
1. Start X11 and stay on the desktop.
2. Grab some area large enough (2/3 of the screen).
3. Frame is going to get pretty slow and laggy.

Yea, it's not a problem itself because it's just a smoothness issue, but I believe something really messy is going on after such a simple action, because of these logs:
`[ 2269.351131] vc4-drm soc:gpu: failed to allocate buffer with size 946176
[ 2269.682454] vc4-drm soc:gpu: failed to allocate buffer with size 3010560
[ 2269.780828] vc4-drm soc:gpu: failed to allocate buffer with size 1056768
[ 2269.782802] vc4-drm soc:gpu: failed to allocate buffer with size 1056768
[ 2269.782872] vc4-drm soc:gpu: failed to allocate buffer with size 1056768
[ 2269.786145] [drm:vc4_validate_bin_cl [vc4]] *ERROR* 0x00000000: packet 112 (VC4_PACKET_TILE_BINNING_MODE_CONFIG) failed to validate
[ 2269.791092] vc4-drm soc:gpu: failed to allocate buffer with size 1077248
[ 2269.791163] vc4-drm soc:gpu: failed to allocate buffer with size 1077248
[ 2269.794115] [drm:vc4_validate_bin_cl [vc4]] *ERROR* 0x00000000: packet 112 (VC4_PACKET_TILE_BINNING_MODE_CONFIG) failed to validate
[ 2269.796577] vc4-drm soc:gpu: failed to allocate buffer with size 1056768
[ 2269.796648] vc4-drm soc:gpu: failed to allocate buffer with size 1056768
[ 2269.799633] [drm:vc4_validate_bin_cl [vc4]] *ERROR* 0x00000000: packet 112 (VC4_PACKET_TILE_BINNING_MODE_CONFIG) failed to validate
[ 2269.800149] vc4-drm soc:gpu: failed to allocate buffer with size 3874816
[ 2269.800229] vc4-drm soc:gpu: failed to allocate buffer with size 3874816
[ 2269.802319] vc4-drm soc:gpu: failed to allocate buffer with size 3874816
[ 2269.802379] vc4-drm soc:gpu: failed to allocate buffer with size 3874816
[ 2269.805062] vc4-drm soc:gpu: failed to allocate buffer with size 3874816
[ 2269.805298] vc4-drm soc:gpu: failed to allocate buffer with size 3874816
[ 2269.810274] vc4-drm soc:gpu: failed to allocate buffer with size 3874816
[ 2269.810357] vc4-drm soc:gpu: failed to allocate buffer with size 3874816
[ 2269.810740] vc4-drm soc:gpu: failed to allocate buffer with size 3874816
[ 2269.811020] vc4-drm soc:gpu: failed to allocate buffer with size 3874816
[ 2269.815098] vc4-drm soc:gpu: failed to allocate buffer with size 3874816
[ 2269.815333] vc4-drm soc:gpu: failed to allocate buffer with size 3874816
[ 2269.818591] vc4-drm soc:gpu: failed to allocate buffer with size 3874816
[ 2269.818671] vc4-drm soc:gpu: failed to allocate buffer with size 3874816
[ 2269.820081] vc4-drm soc:gpu: failed to allocate buffer with size 3874816
[ 2269.820344] vc4-drm soc:gpu: failed to allocate buffer with size 3874816
[ 2269.824405] vc4-drm soc:gpu: failed to allocate buffer with size 3874816
[ 2269.824472] vc4-drm soc:gpu: failed to allocate buffer with size 3874816
[ 2269.825065] vc4-drm soc:gpu: failed to allocate buffer with size 3874816
[ 2269.825125] vc4-drm soc:gpu: failed to allocate buffer with size 3874816
[ 2269.878325] vc4-drm soc:gpu: failed to allocate buffer with size 1056768
[ 2269.878437] vc4-drm soc:gpu: failed to allocate buffer with size 1056768
[ 2269.878474] [drm:vc4_validate_bin_cl [vc4]] *ERROR* 0x00000000: packet 112 (VC4_PACKET_TILE_BINNING_MODE_CONFIG) failed to validate
[ 2269.878836] vc4-drm soc:gpu: failed to allocate buffer with size 1077248
[ 2269.878898] vc4-drm soc:gpu: failed to allocate buffer with size 1077248
[ 2269.886150] [drm:vc4_validate_bin_cl [vc4]] *ERROR* 0x00000000: packet 112 (VC4_PACKET_TILE_BINNING_MODE_CONFIG) failed to validate
[ 2269.954415] vc4-drm soc:gpu: failed to allocate buffer with size 1064960
[ 2269.959146] vc4-drm soc:gpu: failed to allocate buffer with size 2150400
[ 2269.959347] vc4-drm soc:gpu: failed to allocate buffer with size 2150400
[ 2269.963551] vc4-drm soc:gpu: failed to allocate buffer with size 2150400
[ 2269.963614] vc4-drm soc:gpu: failed to allocate buffer with size 2150400
[ 2269.964342] vc4-drm soc:gpu: failed to allocate buffer with size 2150400
[ 2269.964404] vc4-drm soc:gpu: failed to allocate buffer with size 2150400
[ 2269.968520] vc4-drm soc:gpu: failed to allocate buffer with size 2150400
[ 2269.968583] vc4-drm soc:gpu: failed to allocate buffer with size 2150400
[ 2269.972295] vc4-drm soc:gpu: failed to allocate buffer with size 2150400
[ 2269.972354] vc4-drm soc:gpu: failed to allocate buffer with size 2150400
[ 2269.973469] vc4-drm soc:gpu: failed to allocate buffer with size 2150400
[ 2269.973528] vc4-drm soc:gpu: failed to allocate buffer with size 2150400
[ 2269.975294] vc4-drm soc:gpu: failed to allocate buffer with size 2150400
[ 2269.975351] vc4-drm soc:gpu: failed to allocate buffer with size 2150400
[ 2269.975379] [drm:vc4_bo_create [vc4]] *ERROR* Failed to allocate from CMA:
[ 2269.975384] [drm] num bos allocated: 626
[ 2269.975388] [drm] size bos allocated: 212388kb
[ 2269.975392] [drm] num bos used: 624
[ 2269.975396] [drm] size bos used: 208188kb
[ 2269.975400] [drm] num bos cached: 2
[ 2269.975404] [drm] size bos cached: 4200kb
[ 2269.976735] vc4-drm soc:gpu: failed to allocate buffer with size 2150400
`

**Comment by anholt** [comment]
Lots of missing information here:
- What desktop are you running?  What distro?
- What kernel version are you using?  Please attach dmesg output as a file rather than a snippet.
- What does "grab some area" mean?  Are you moving a window?

**Comment by cringeops** [comment]
@anholt My bad, totally forgot to mention.

Raspbian Jessie, LXDE, kernel 4.4.23-v7+. I meant to select the area on the desktop screen. If you rapidly move the pointer from one edge to another while selecting objects on the desktop, the selection square will become slow and laggy. And this action will produce VC4 debug messages in dmesg.

There is full dmesg output (last lines contain debug messages) [https://drive.google.com/open?id=0BzaLGbseIvGJMTd5Wm9BMTJKTkk](url)

**Comment by anholt** [comment]
OK, brought it up in sysprof.  Not a great profile because sysprof is failing to get callgraphs in userspace (sigh, ARM performance debugging).

pcmanfm looks like it's doing some pretty basic Cairo-based compositing.  Presumably it has its copy of the unselected desktop.  Make a temporary pixmap the size of the selection, copy unselected over to it, composite the rectangle over that, then copy that result to the screen.

Some places where we're hurting:

### 24% memcpy

We'll take a note of this as a single thing because we don't have callgraphs, and it should mostly be charged to various things below.

### 8.3% `pixman_rasterize_edges()`

The biggest problem is probably that we're doing software rasterization of the traps.  We're spending this much time in the rasterizer, but there's also a bunch of memcpy overhead getting it out of the rasterizer into a texture.  If we did hardware traps (should be doable!) this would go away.

### 3.5% Power management of the GPU

Right now we don't tell runtime PM to hold onto device power for a while before shutting it down when idle, so we spend a bunch of time here.  Past attempts to show performance difference here didn't get anything, but we clearly have a problem.

### 2.1% BO allocation in the kernel

The temporary pixmaps mean hitting our allocator a lot, and this workload is unusual for 3D in that it keeps asking for different sizes.  One quick fix might be to allow smaller allocations to be satisfied by bigger cached memory, but that would only fix the lag as your rectangle gets slower.  You could round up allocations more so that the next bigger one hits the cache (right now, we only round by 4k, in other words, almost nothing).

### 1.0% `vc4_store_tiled_image()` + `vc4_store_utile()`

Uploading textures (in this case, the software-rasterized trapezoid mask) has never been optimized.  The cost here is understated, as a bunch of the `__aeabi_uidiv()` should also be charged to this (and we could easily not even cause that) and there's a bunch of memcpy() too.

### 0.9% `vc4_load_tiled_image()` + `vc4_load_utile()`

Similar to above, except what in this path would even be reading back from textures?  This is really suspicious, as `GLAMOR_DEBUG=1` doesn't show any fallbacks.  gdb on Xorg shows it happening in `st_TexImage() -> st_TexSubImage() -> vc4_resource_transfer_map()`.  This is broken, let's fix it first.

**Comment by anholt** [comment]
Landed a fix for the unnecessary loading, which cuts the memcpy overhead by about half.

In my testing on master (kernel, X, mesa), I haven't seen any validate failures due to memory allocation failure.  Nothing in this path should be causing that, so I also need to look into that on downstream.

**Comment by cringeops** [comment]
@anholt Nice work, I'll try to report driver bugs and debug messages to you, because my Pi is always on heavy duty, so I'm interested in getting raspberry more stable.

Yes, Eric, while I remember. Something is wrong with diagonal lines rendering. Install chemtool and try to draw benzene ring. All straight lines will be rendered fine, but diagonal ones will be ghosts.

**Comment by anholt** [comment]
I've merged a fix for the PM problem upstream, and have it in a PR for downstream.  Once I land the NEON optimization for vc4_store_tiled_image(), I'll probably close this bug out.

**Comment by anholt** [comment]
NEON code is in.  I think I'll consider this bug done.
