### ISSUE TITLE
Fill thread switch delay slots

### ISSUE THREAD

**Issue by jonasarrow** [anholt/mesa#54]
The thread switch signal takes two additional instructions to work. Currently we emit NOP's in them.
https://github.com/jonasarrow/mesa_freedesktop/commit/60cfa7f54da965c1a5aa8f4fa7c02a7b066136f0 tries to shift the signal upwards to omit these NOPs.

It works well for some tests I've done. It works not optimal, because the switch signal itself is emitted on a NOP, so this NOP is kept in the shader, even if it could be optimized out.

**Comment by anholt** [comment]
Started taking a look at your code today.  Fixed validation failures in lots of apps with:

    -                                qpu_serialize_one_inst(c, inst);
    +                                qpu_serialize_one_inst(c, qpu_NOP());

This makes me wonder if, right before we do the general qpu_serialize_one_inst(), we could check if it's the just-the-thrsw instruction and instead call a helper function that walks backwards, inserts the signal, inserts delay nops, and returns, instead of doing our fixups after inserting.

I also noticed that your code was only looking in the previous 2 instructions, when I think we could look at inserting into last-3, too.  In piglit's glsl-fs-texture2dproj, that gets us:

    FS prog 1/1 QPU:
    0x100049e0203e303e nop nop, r0, r0 ; fmul r0, vary, ra15
    0x10024860213e317e fadd r1, r0, r5 ; fmul r0, vary, ra15
    0x60020827019e7140 sig_thread_switch fadd r0, r0, r5 ; nop nop, r0, r0
    0xd00049f9209ef007 sig_small_imm nop nop, r0, r0 ; fmul tmu0_t, r0, 0.500000
    0xd00049f8209ef00f sig_small_imm nop nop, r0, r0 ; fmul tmu0_s, r1, 0.500000
    0x100009e7009e7000 nop nop, r0, r0 ; nop nop, r0, r0
    0xa00009e7009e7000 load_tmu0 nop nop, r0, r0 ; nop nop, r0, r0

(one less nop, just the one that held the thrsw is left)

**Comment by anholt** [comment]
OK, landed a pair of patches for this.  One was your mostly as-is (just piglit regression fixes) then another that cut the other NOP case out.  Thanks!
