### ISSUE TITLE
Enable drivers on Pi 0/1

### ISSUE THREAD

**Issue by jextrevor** [anholt/mesa#55]
The [wiki](https://github.com/anholt/mesa/wiki/VC4) states that the drivers are compatible with Pi 0/Pi 1, but that raspi-config refuses to enable them.

How would one go about installing and enabling these drivers on the less powerful Pi's?

**Comment by jonasarrow** [comment]
Modify `config.txt`

    gpu_mem=16
    dtoverlay=vc4-kms-v3d
    avoid_warnings=2

Modify `cmdline.txt`

    cma=128M@64M

If you need more/less GPU memory, adjust the cma line. The first parameter is the size, the second the start address in memory. So here the GPU has 128 MB memory. Note, that this memory can be used by the ARM by default. These settings work even for the 256 MB Pis.

**Comment by mskwon** [comment]
There seems to be an issue since the recent Raspbian package update and the switch to Compton. I enabled vc4 on a RPi 1B by modifying raspi-config to get rid of the if block checking for the RPi 0/1 and modifying config.txt to have the following: 

dtoverlay=vc4-kms-v3d,cma-128

which worked before the update. Since the update, LXDE seems to crash if moving the mouse as the desktop gets loaded. A relevant excerpt from the dmesg:
> [  171.455739] vc4-drm soc:gpu: failed to allocate buffer with size 8355840
[  171.455949] vc4-drm soc:gpu: failed to allocate buffer with size 8355840
[  171.456085] vc4-drm soc:gpu: failed to allocate buffer with size 8355840
[  171.456190] vc4-drm soc:gpu: failed to allocate buffer with size 8355840
[  171.456425] [drm:vc4_bo_create [vc4]] *ERROR* Failed to allocate from CMA:
[  171.456572] [drm] num bos allocated: 89
[  171.456586] [drm] size bos allocated: 120796kb
[  171.456598] [drm] num bos used: 87
[  171.456612] [drm] size bos used: 104476kb
[  171.456686] [drm] num bos cached: 2
[  171.456700] [drm] size bos cached: 16320kb

I've attached two different dmesg logs, the first is with drm.debug=0x1f in the cmdline.txt and the second is without. 

I am using the most recent firmware available via rpi-update and the most recent Raspbian packages as of 12/10/2016
[cmdline.txt](https://github.com/anholt/mesa/files/644042/cmdline.txt)
[config.txt](https://github.com/anholt/mesa/files/644041/config.txt)
[dmesg.txt](https://github.com/anholt/mesa/files/644043/dmesg.txt)
[dmesg2.txt](https://github.com/anholt/mesa/files/644044/dmesg2.txt)

What's going on?

EDIT: Perhaps related? https://github.com/raspberrypi/linux/issues/1354

**Comment by anholt** [comment]
Pi0/1 should be doing a lot better since the binner rework to allow more CMA memory, back in March.

**Comment by anholt** [comment]
Looks like raspi-config got fixed in 1314529716207877ee52cd7d5d3405c84529b8a3, so I'm marking this closed.
