### ISSUE TITLE
Register allocation issues regressed from 11.1.0-1+rpi1 to 13.0.0-1+rpi1

### ISSUE THREAD

**Issue by gohai** [anholt/mesa#63]
With the latest Raspbian release, and updates (`libgles2-mesa` is at `13.0.0-1+rpi1`), I am seeing register allocation errors in Processing for every P3D example I try.
This is with the `vc4-kms-v3d` overlay ("OpenGL desktop driver with full KMS"). I haven't tried the hybrid option.

@anholt Any idea what's causing this? I remember you writing about testing Processing yourself - was this against a different Mesa branch? (Which setup would make the most sense for me to test currently?) Thanks!

----

Steps to reproduce (with the aforementioned setup):
* `curl https://processing.org/download/install-arm.sh | sudo sh`
* `processing-java --sketch=/usr/local/lib/processing/modes/java/examples/Basics/Camera/MoveEye --run`

Output:
* [MoveEye-out.txt](https://github.com/anholt/mesa/files/783563/MoveEye-out.txt)

**Comment by gohai** [comment]
This is a regression from Mesa `11.1.0-1+rpi1` to `13.0.0-1+rpi1`. Please close if this is a known issue - happy to provide information if required.

**Comment by anholt** [comment]
Looking at this sketch on Mesa 17, we're at ~77 registers of reg pressure, while the hardware only has ~69 registers available and no ability to spill.

Turning on GCM gets this one compiling again, though that's going to take some more investigation before we can land it (it hurts in instruction count on various apps, but instruction count is a poor proxy for performance when you're potentially jumping across more instructions).  GCM is causing the unrolled loop's IF statements to stay unflattened, which I guess saves us a couple of temps (or maybe it just managed to actually sink some temps down to their usage).

One possible fix would have been to move some of the VPM loads to the end of the program right before we use them, since we've got a few regs that aren't used until after the giant block (we have code that does this in some cases, but is disabled when there's control flow because the logic needs fixing).  

However, that ends up not working because we use the last vertex attribute from within the loop, and VC4 requires that we load the vertex attributes in order.  To work around that, we'd need to introduce a map between the API-level vertex attribute index and the HW-level index so that they appear in the order we want.  That wouldn't be too hard.

**Comment by gohai** [comment]
Thanks for looking into this, Eric! Is there anything we could do short-term with the shader, to make it easier for the compiler? (We're already shipping a special version for both Broadcom drivers that reduce the number of lights to a maximum of two - see [LightVert-vc4.glsl](https://github.com/processing/processing/blob/master/core/src/processing/opengl/shaders/LightVert-vc4.glsl#L100) and [TexLightVert-vc4.glsl](https://github.com/processing/processing/blob/master/core/src/processing/opengl/shaders/TexLightVert-vc4.glsl#L103))

**Comment by anholt** [comment]
I'd say it's the conditional break within the loop that's killing things -- if you could #define the number of lights, that would surely make it easy enough to schedule.

input reordering is looking good:
```
total instructions in shared programs: 76666 -> 76590 (-0.10%)
instructions in affected programs:     42945 -> 42869 (-0.18%)
total max temps in shared programs: 9395 -> 9208 (-1.99%)
max temps in affected programs:     2951 -> 2764 (-6.34%)
```

but GCM is looking bad:
```
total instructions in shared programs: 76590 -> 77423 (1.09%)
instructions in affected programs:     15343 -> 16176 (5.43%)
total max temps in shared programs: 9208 -> 9246 (0.41%)
max temps in affected programs:     472 -> 510 (8.05%)
```

**Comment by anholt** [comment]
We may also just want to not unroll loops when they have conditional breaks in them that mean that you have to conditionalize the entire body of each unrolled section.  It's not like you're getting anything out of unrolling, at that point.

**Comment by anholt** [comment]
Merged the input load delay code.  Looks like `nir_lower_io_to_temporaries()` on inputs prevents it from taking full effect, without GCM to fix it back up.  Dropping the lowering on inputs still only gets us down to 70 registers, though.

**Comment by gohai** [comment]
Thanks for this! I've tried removing the `break` from the shader, in an effort to get it to work with `13.0.0-1+rpi1`, but this still trips up. Guess we'll have to wait for GCM and your other improvements to land and trickle down to Raspbian.

In any way: thanks for investigating (your commit about tracking max temps vs general instruction count makes it feel like this is such a sisyphean task, trying to square the circle).

**Comment by gohai** [comment]
(Or we'll tell people to stay a bit longer on the current Raspbian release. Mesa 11.1 has been a "good year" for us, with all but 5 out of 86 OpenGL examples working!)

**Comment by gohai** [comment]
@anholt I was just looking at this again, seeing if we can do anything extra in our shader - and it turns out that reducing the number of maximum lights (= loops) to two is sufficient to not run out of registers. We had to use a similar hack on the closed driver, so this isn't so much a regression or anything really. (I'll try every now and then to see if we can fit it a couple more lights, but for now let me close this issue.)
