### ISSUE TITLE
Processing example triggers crash in vc4_dri.so

### ISSUE THREAD

**Issue by gohai** [anholt/mesa#65]
(Just reporting this because I have an easy reproducer, this just affects a single example, and most likely first caused by something that we're doing wrong, but here it goes:)

Running the `Topics/Shaders/SepBlur` example causes a crash in `vc4_dri.so`. I don't have a meaningful stack trace on the C side, but the Java one looks like this:

    Native frames: (J=compiled Java code, j=interpreted, Vv=VM code, C=native code)
    C  [vc4_dri.so+0x658598]

    Java frames: (J=compiled Java code, j=interpreted, Vv=VM code)
    j  jogamp.opengl.gl4.GL4bcImpl.dispatch_glDrawElements1(IIIJJ)V+0
    j  jogamp.opengl.gl4.GL4bcImpl.glDrawElements(IIIJ)V+53
    j  processing.opengl.PJOGL.drawElementsImpl(IIII)V+10
    j  processing.opengl.PGL.drawElements(IIII)V+16
    j  processing.opengl.PShader.draw(III)V+27
    j  processing.opengl.PGraphicsOpenGL.flushPolys()V+603
    j  processing.opengl.PGraphicsOpenGL.flush()V+181
    j  processing.opengl.PGraphicsOpenGL.endDraw()V+16
    j  SepBlur.draw()V+102

I believe I already reported this to you in private in 2015. Back then the crash was in `ntq_get_src at vc4_program.c:155`, but unsure if this is the same thing.

Anyway, the steps to reproduce:

* `curl https://processing.org/download/install-arm.sh | sudo sh`
* `processing-java --sketch=/usr/local/lib/processing/modes/java/examples/Topics/Shaders/SepBlur --run`

**Comment by jonasarrow** [comment]
Can reproduce the issue, signal raised is `SIGBUS`, at `nir_visitor::visit(ir_constant *ir)`.

> [ 2990.581551] Alignment trap: not handling instruction f44607df at [<62584ec8>]
> [ 2990.581580] Unhandled fault: alignment exception (0x801) at 0x647abca4
> [ 2990.588212] pgd = ac9e0000
> [ 2990.590925] [647abca4] *pgd=2c9f4831, *pte=0d68575f, *ppte=0d685c7f

Interestingly, if I build mesa with `-O0 -ggdb -march=cortex-a7 -mfpu=neon-vfpv4`, the error goes away and the sample runs just fine. 
Testing with `-O2 -ggdb -march=cortex-a7 -mfpu=neon-vfpv4` still works. 
Testing with `-march=cortex-a7 -mfpu=neon-vfpv4` still works.
Testing with `-O3 -march=cortex-a7 -mfpu=neon-vfpv4` does NOT work. So I would say, there is a bug in the optimizer of GCC at `-O3`.

Using GDB (and some hacking to get GDB attached to the real process crashing), the crash occurs at:
> constant_copy (mem_ctx=0x61af8614, ir=0x648b3824) at glsl/glsl_to_nir.cpp:242
> 242	      for (unsigned c = 0; c < cols; c++) {
More precisely at 
> visit(ir_constant*)+976>        vst1.64        {d16}, [r6 :64]

With `r6` is `0x648bf38c` and therefore not 64 byte aligned, which leads correctly to an alignment fault.

Why does GCC generate a vst1.64 here, if it cannot guarantee the alignment requirement and when generating, why enforce the alignment, which is optional?

All test are done with current mesa, cross-compiled with `distcc` and the current [github.com/raspberrypi/tools](github.com/raspberrypi/tools) toolchain.

**Comment by jonasarrow** [comment]
I now think, I might know the root cause for the error. 

Mesa uses the `ralloc` allocator, which prepends every allocation with a header to track the allocations and provide convenient freeing at a single point. The header contains (in the non-debug case) 5 pointers (parent, sibling prev and next, and a destructor), which makes it a size of  20 bytes. Directly after the header follows the actual allocated memory. All the `ralloc` functions are `__attribute__((malloc))`'ed, so GCC assumes a alignment of 8 bytes (aligment of `double`, which is a native C type) and therefore thinks, it is save to generate a instruction, which assumes a alignment of 8 bytes, this assumption is almost any time (when using memory from the `ralloc` allocator) violated, leading to a crash in the first case, when it matters (e.g. using vectorized loops, activated by `-O3`).

Solution:
Make the structure 8 byte aligned by aligning the structure to 8 bytes size. The best thing would be forcing a 8 byte alignment.

EDIT:
Working patch is at https://github.com/jonasarrow/mesa_freedesktop/commit/9f3590a481aeb89745c9fd7de0c4cb936b2c1279 .

**Comment by anholt** [comment]
Pulled the patch, edited the commit message, and forwarded to mesa-dev for review.  Thanks for debugging, @jonasarrow!

**Comment by gohai** [comment]
Thanks also from my side, @jonasarrow. I probably won't be able to test this anytime soon, but when I get around to re-building Mesa on my Pi I sure will.

**Comment by jonasarrow** [comment]
Tested it with current mesa from git, it works now.
