### ISSUE TITLE
Enable NEON assembly in ARMv6 builds

### ISSUE THREAD

**Issue by anholt** [anholt/mesa#69]
RPi builds for ARMv6, but we still want the NEON support in a Pi2/Pi3 to be detected and used, to improve texture upload/download performance.  Need to extend util_cpu_detect() for ARM and use it.

**Comment by Decatf** [comment]
So runtime NEON detection landed in upstream mesa. Is it still working for non-NEON RPi? What build configuration do you use to compile for non-NEON ARM devices?

I am asking because a problem is that with runtime detection the vc4 driver requires `-mfpu=neon` cflag. So Alpine Linux enabled this cflag globally for mesa in order to fix the compile errors ([see here](https://git.alpinelinux.org/cgit/aports/commit/main/mesa/APKBUILD?id=2b4535bd3025886a5237ecf385fe5f92b8c28da2)).   

This breaks runtime on non-NEON devices because the compiler itself can generate NEON opcodes anywhere. I think maybe the `-mfpu=neon` flag could be specified per file where hand coded NEON optimizations exist. Otherwise the compiler could emit NEON opcodes on the non-NEON paths too. Is this how it's being compiled for non-NEON RPi? Would this be a better way rather than having the build maintainer or distro packaging do it right?  

I'm not using an RPi but an Android Tegra 2 tablet with Alpine Linux. With the Android build environments they've largely neglected non-NEON configurations leaving my device out of luck for a lot of applications and libraries. I'm hoping that this issue can be prevented with the Linux userspace.

**Comment by jonasarrow** [comment]
A fix for the compiler problem is https://github.com/jonasarrow/mesa_freedesktop/commit/e8c493a091d74f43e4797f79c8d409dde277f50a. 
Render looks fine. I don't know, if NEON is called (RPI 3).

EDIT: Tested not this compilation but the standard-one in raspbian. But it should work just as fine.
EDIT2: Now used my binaries on RPI 3 and RPI 1B(256M), both time it works and on RPI 3 the NEON-path is used, on the RPI 1 the base path is called, so working as expected and getting my tested-by.

**Comment by jonasarrow** [comment]
https://github.com/jonasarrow/mesa_freedesktop/commit/ea2afc19b1a8ccd4e0cd01ca654b4c5a1d6b5071 is the more complete solution working under most circumstances (cross compile, compile with the wrong kernel, native compile, setting CFLAGS).

**Comment by Decatf** [comment]
I have tested the first solution on Alpine Linux with mesa 17.1.4 on my Tegra 2 device (not RPI due to not having the hardware). With the mesa package installed from Alpline repository Xwayland will crash with SIGILL ILL_ILLOPC.  After applying the first solution the mesa package compiles without needing to set `-mfpu=neon` globally. And Xwayland will run without illegal opcode errors.

I did not test the second solution since the patch does not apply due to more significant changes in the VC4 driver after mesa 17.1.x. In principle the solution should work. As long as the VC4 driver will still work and not need `-mpu=neon` flag beyond the scope of the hand written NEON parts.

**Comment by anholt** [comment]
There's a series for this on the mailing list now -- I took a different approach from @jonasarrow, just switching on the CPU we're building for, and reducing duplicated builds when unnecessary.  It's also enabled for Android, finally.

Alpine Linux should definitely not be adding a global -mfpu=neon.

**Comment by anholt** [comment]
Pushed the fix now.
